Add English Translation for Certificates
admin-ch/CovidCertificate-SDK-Android pull request #7
Opened 2021-06-06 13:55 UTC by benz-ubique

Add English translation for Certificates. If the system lang. is english do not show any other translation

2021-06-06 19:40 UTC, goebelUB approved these changes

2021-06-07 06:13 UTC, M-Wong requested changes

2021-06-07 06:13 UTC, M-Wong commented on sdk/src/main/java/ch/admin/bag/covidcertificate/eval/utils/RecoveryEntryUtils.kt
>  	return try {
This whole country string logic is the same for recoveries, tests and vaccinations. Should we extract the logic into a separate Utils class and only pass in the `co` from the *Entry?

2021-06-08 05:59 UTC, M-Wong approved these changes

2021-06-08 05:59 UTC, merged